# Generated by Django 4.2.1 on 2023-07-24 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CounsellingApp', '0005_answeruser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookingdate', models.CharField(max_length=100)),
                ('dateofbook', models.DateField(auto_now_add=True)),
                ('status', models.CharField(max_length=100)),
                ('councelr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CounsellingApp.counsilerregistration')),
                ('usr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CounsellingApp.userregistration')),
            ],
        ),
        migrations.CreateModel(
            name='Authmessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messages', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('usr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CounsellingApp.userregistration')),
            ],
        ),
    ]
