# Generated by Django 4.2.1 on 2023-07-24 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CounsellingApp', '0006_booking_authmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='request',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='booking',
            name='typ',
            field=models.CharField(default='', max_length=100),
        ),
    ]
