# Generated by Django 4.2.1 on 2023-07-25 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CounsellingApp', '0008_counsilerregistration_aboutme'),
    ]

    operations = [
        migrations.AddField(
            model_name='counsilerregistration',
            name='video',
            field=models.ImageField(null=True, upload_to='video'),
        ),
    ]
