# Generated by Django 4.2.3 on 2023-07-26 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CounsellingApp', '0009_counsilerregistration_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mytab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('usr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CounsellingApp.userregistration')),
            ],
        ),
    ]
