# Generated by Django 4.2.3 on 2023-08-19 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CounsellingApp', '0010_mytab'),
    ]

    operations = [
        migrations.AddField(
            model_name='authmessage',
            name='video',
            field=models.ImageField(null=True, upload_to='video'),
        ),
    ]
