# Generated by Django 4.2.3 on 2023-08-19 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CounsellingApp', '0011_authmessage_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=50)),
                ('date', models.DateField(auto_now_add=True)),
                ('con', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CounsellingApp.counsilerregistration')),
                ('usr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CounsellingApp.userregistration')),
            ],
        ),
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now_add=True)),
                ('usr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CounsellingApp.userregistration')),
            ],
        ),
    ]
