# Generated by Django 4.2.3 on 2023-08-19 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CounsellingApp', '0012_payment_feedback'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='feedback',
            new_name='feedbackss',
        ),
    ]
